### ISSUE TITLE
Break same name with R

### ISSUE THREAD

**Issue by kootenpv** [iamaziz/PyDataset#6]
I always thought having the name "data" as a function globally is one of the weirdest things in R.
Perhaps consider changing it into `load_data` (comparable to `load_xxxx` in sklearn).
Then people can use `data` (however vague that term is anyway) in their scripts freely.

**Comment by iamaziz** [comment]
At the beginning, I was not sure what to call it, then just decided to keep it as simple as possible. And with that name, displaying the documentation (as well as displaying the existing datasets) would still make sense and does not need to have a separate function name for each. 
But (thanks to [Thomas Wouters](http://legacy.python.org/dev/peps/pep-0221/)) you can always call it whatever you like :-) just 

``` python
from pydataset import data as load_some_awesome_dataset
```
